name: Deploy blog  # 工作流名称

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches:
      - main
  # 手动触发部署
  workflow_dispatch:

jobs:
  deploy-gh-pages:  # 定义作业名称
    runs-on: ubuntu-latest  # 运行在虚拟机环境 ubuntu-latest

    steps:
      - name: Checkout  # 步骤 1
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 7
          # 使用 pnpm 安装依赖
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 pnpm 依赖
          cache: pnpm
      
      - name: Install Deps
        run: pnpm install --frozen-lockfile

      # 运行构建脚本
      - name: Build Blog
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/JamesIves/github-pages-deploy-action
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署到 gh-pages 分支
          branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          folder: dist

